# Generated by Django 4.0.6 on 2023-03-23 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_things_you_wil_learn_course_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course')),
            ],
        ),
        migrations.AlterModelOptions(
            name='course_requirements',
            options={'verbose_name_plural': 'Course Requirement'},
        ),
        migrations.AlterModelOptions(
            name='things_you_wil_learn',
            options={'verbose_name_plural': 'things you wil learn'},
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(blank=True, max_length=100, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='Images/Video_imgs')),
                ('title', models.CharField(max_length=100)),
                ('youtube_id', models.CharField(max_length=100)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('preview', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lesson')),
            ],
        ),
    ]
