# Generated by Django 4.0.6 on 2023-03-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_lesson_alter_course_requirements_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='speacailty',
            field=models.CharField(default='web dev', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='serial_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
