# Generated by Django 4.0.6 on 2023-03-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_author_speacailty_alter_video_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
