# Generated by Django 4.0.6 on 2023-03-23 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_alter_video_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='speacailty',
            new_name='specialty',
        ),
    ]
